/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class AdminPass extends javax.swing.JPanel {

    public AdminPass() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldPw = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newPw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        newPw2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        statLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(304, 176));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Change Admin Password");
        add(jLabel1);
        jLabel1.setBounds(10, 0, 299, 31);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Old Password:");
        add(jLabel2);
        jLabel2.setBounds(65, 50, 90, 30);
        add(oldPw);
        oldPw.setBounds(160, 50, 150, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("New Password:");
        add(jLabel3);
        jLabel3.setBounds(60, 90, 90, 30);

        newPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPwActionPerformed(evt);
            }
        });
        newPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPwKeyTyped(evt);
            }
        });
        add(newPw);
        newPw.setBounds(160, 90, 150, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Re-Type New Password:");
        add(jLabel4);
        jLabel4.setBounds(10, 130, 140, 30);
        add(newPw2);
        newPw2.setBounds(160, 130, 150, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Password Status : ");
        add(jLabel6);
        jLabel6.setBounds(55, 170, 110, 30);

        statLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        add(statLbl);
        statLbl.setBounds(160, 170, 150, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void newPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPwKeyReleased
        String npass = newPw.getText();
        String rpass = newPw2.getText();

        if (npass.length() <= 1) {
            statLbl.setForeground(new Color(204,0,0));
            statLbl.setText("Weak Password");  
            status = "weak";
        }
        if (npass.length() == 5) {
            statLbl.setForeground(new Color(255,190,0));
            statLbl.setText("Good Password");
            status = "good";
        }
        if (npass.length() >= 9) {
            statLbl.setForeground(new Color(0,204,0));
            statLbl.setText("Strong Password");
            status = "strong";
        } 
        else {

        }
// TODO add your handling code here:
    }//GEN-LAST:event_newPwKeyReleased
    int passwordCheck = 0;
    String pass = "";
    public static String status = "";

    private void newPwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPwKeyTyped
        char c = evt.getKeyChar();
        if (Character.isUpperCase(c)) {
            pass += "upper";

        }
        if (Character.isLowerCase(c)) {
            pass += "lower";

        }
        if (Character.isDigit(c)) {
            pass += "number";

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_newPwKeyTyped

    private void newPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPwActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JPasswordField newPw;
    public static javax.swing.JPasswordField newPw2;
    public static javax.swing.JPasswordField oldPw;
    private javax.swing.JLabel statLbl;
    // End of variables declaration//GEN-END:variables
}
